server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sun-hongwei/microservice-config.git #GitHub上面的git仓库名字

      #http://config-3344.com:3344/application-dev.yml
      #http://config-3344.com:3344/application/dev/master
      #http://config-3344.com:3344/master/application-dev.yml